export {default as Home} from './Home'
export {default as Public} from './Public'
export {default as Login} from './Login'
export {default as AlbumDetail} from './AlbumDetail'
export {default as Album} from './Album'
export {default as Artist} from './Artist'
export {default as ArtistDetail} from './ArtistDetail'