const actionTypes = {
    SET_CUR_SONG_ID: 'SET_CUR_SONG_ID',
    PLAY: "PLAY",
    SET_RECENT_SONGS: 'SET_RECENT_SONGS',
    SET_QUEUE_SONGS: 'SET_QUEUE_SONGS',
    SET_FAVOURITE_SONGS: 'SET_FAVOURITE_SONGS',
    SET_IS_FAVOURITE: 'SET_IS_FAVOURITE'
}
export default actionTypes;