const actionTypes = {
    SET_CUR_SONG_ID: 'SET_CUR_SONG_ID',
    PLAY: "PLAY",
    SET_RECENT_SONGS: 'SET_RECENT_SONGS',
    SET_FAVOURITE_SONGS: 'SET_FAVOURITE_SONGS',
    SET_IS_FAVOURITE: 'SET_IS_FAVOURITE'
    // SET_FAVOURITE_SONG: 'SET_FAVOURITE_SONG',
    // ADD_FAVOURITE_SONG: 'MUSIC_FAVOURITE',
    // REMOVE_FAVOURITE_SONG: 'REMOVE_FAVOURITE_SONG'
}
export default actionTypes;